apiVersion: v1
kind: Pod
metadata:
  name: ${project.artifactId}
spec:
  containers:
    - name: ${project.artifactId}
      image: test/${project.artifactId}:0.0.1
      env:
#        JDK 10
#        - name: JAVA_OPTS
#          value: "-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError"
#        JDK 8 & 9
        - name: JVM_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xmx300M"
      resources:
        requests:
          memory: "64Mi"
          cpu: 1
        limits:
          memory: "370Mi"
          cpu: 2
  restartPolicy: OnFailure